version: 2
executorType: docker

containerInfo:
  - image: 1science/sbt:latest
  - image: postgres:latest
    env:
      - POSTGRES_DB=stout
      - POSTGRES_USER=stout
      - POSTGRES_PASSWORD=stout
      - POSTGRES_HOST="localhost"
      - POSTGRES_PORT="5432"

stages:
  build:
    workDir: ~/stout
    steps:
      - type: shell
        name: Installing dependencies
        command: |
          apk update &&
          apk add git openssh

      - checkout

      - type: shell
        name: Database migrations
        command: sbt flywayClean flywayMigrate

      - type: shell
        name: Tests
        command: sbt test:test
